### PR TITLE
Fix CORS issue for custom plugins

### LINKED ISSUE #380: The "Custom Plugin" option doesn't work.
**Describe the bug**

The "Custom Plugin" option doesn't work.

**To Reproduce**
1. Go to "Plugins"
2. Click on "Custom Plugin"
3. Enter for example "https://www.instacart.com/.well-known/ai-plugin.json" or "https://ai.listennotes.com/.well-known/ai-plugin.json"
4. See the error "Could not validate OpenAI manifest. Failed to fetch https://ai.listennotes.com/.well-known/ai-plugin.json"

**Expected behavior**
Possibility of adding a custom plugin

**Platform**
 - OS: [e.g. Windows]

### PR DESCRIPTION
**Pull request by dehoward**
### Motivation and Context

fixes #380.

**Instacart plugin:**
image
image

**Listennotes plugin:**
image
image

### Description
moves the fetching of the custom plugin's manifest to the backend to avoid the [CORS policy](https://web.dev/cross-origin-resource-sharing/) enforced by browsers.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

File: webapp/src/components/open-api-plugins/plugin-wizard/steps/ValidateManifestStep.tsx [hunk 1]
```diff
@@ -68,38 +69,33 @@ export const ValidateManifestStep: React.FC<IValidateManifestStepProps> = ({
         setErrorMessage(errorMessage);
     };
 
+    const { instance, inProgress } = useMsal();
     useEffect(() => {
         setErrorMessage(undefined);
+        AuthHelper.getSKaaSAccessToken(instance, inProgress)
+            .then(async (accessToken) => {
+                const chatService = new ChatService(process.env.REACT_APP_BACKEND_URI as string);
```
Comment (teresaqhoang) [inline webapp/src/components/open-api-plugins/plugin-wizard/steps/ValidateManifestStep.tsx:77]: Rec: add a hook in usePlugins that makes a call to fetch the manifest -- I think we should maintain a pattern of using the hooks to call the service and handle the request response / user action.

**Review by teresaqhoang — CHANGES_REQUESTED** [review]

**Comment by TaoChenOSU** [comment]
We are about to move all plugins to the backend. this may not be necessary once that's done. Let me confirm if we still want to allow users to add custom plugins from the frontend.

**Comment by TaoChenOSU** [comment]
> We are about to move all plugins to the backend. this may not be necessary once that's done. Let me confirm if we still want to allow users to add custom plugins from the frontend.

We will not modify the custom plugin flow in the first iteration. Please ignore the comment.

**Review by alliscode — APPROVED** [review]

**Review by teresaqhoang — APPROVED** [review]

**Review by glahaye — APPROVED** [review]
